version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-crm-gateway-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - php-crm-gateway-network
    depends_on:
      - mysql
      - redis
      - localstack

  nginx:
    image: nginx:alpine
    container_name: php-crm-gateway-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-crm-gateway-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: php-crm-gateway-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: php_crm_gateway
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php-crm-gateway-network

  redis:
    image: redis:alpine
    container_name: php-crm-gateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - php-crm-gateway-network

  localstack:
    image: localstack/localstack:latest
    container_name: php-crm-gateway-localstack
    restart: unless-stopped
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - php-crm-gateway-network

volumes:
  mysql_data:
    driver: local
  localstack_data:
    driver: local

networks:
  php-crm-gateway-network:
    driver: bridge
